title: Street One Journals
email: dojmarket@gmail.com
description: Market Explained
author: Street One Journals
url: "trinhdev.github.io"
baseurl: "/doj"

# Social Profiles
twitter_username:
github_username:
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
sass:
  sass_dir: assets
  style: compressed
exclude:
  - bower_components
theme: false
