backend:
  name: github
  repo: caubaus/doj
  branch: master
  site_domain: mlempen.com

media_folder: "img/uploads"

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{type}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Type', 
          name: 'type', 
          widget: 'select', 
          options: [
            { label: 'Stock', value: 'stock'},
            { label: 'Crypto', value: 'crypto'},
            { label: 'News', value: 'news'},
            { label: 'Option', value: 'option'},
            { label: 'Rumor', value: 'rumor'},
            { label: 'CKVN', value: 'ckvn'},
          ],
          default: ['Stock']
      }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Sub-title', name: 'subtitle', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Background Image', name: 'background', widget: 'image', choose_url: true}
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
